### PR TITLE
Medication Extractor added

### PR DESCRIPTION
**Pull request by julianxcarter**
Support for the CancerRelatedMedication resource has been added. As a reminder, this should be tested against the corresponding PR on the `mcode-extraction-framework` repo. Happy testing!

**Note: To test, this entry should be added to the `extractors` array within `csv.config.json`: 

```
 {
       "label": "medication",
       "type": "CSVCancerRelatedMedicationExtractor",
       "constructorArgs": {
         "filePath": "./data/csv/cancer-related-medication-information.csv"
       }
 }
```

### CODE REVIEW

**Comment by Dtphelan1** [comment]
Likely needs a rebase after DM's changes; will provide a thorough Monday AM

**Comment by kjmahalingam** [comment]
Do we want an update to an example config indicating the extractor details needed? @Dtphelan1 any thoughts on this? I don't know if we have an mCODE example config yet so maybe we don't need this.

**Review by kjmahalingam — APPROVED** [review]
Nice work!

**Review by Dtphelan1 — APPROVED** [review]
After the `package-lock` is updated, this looks good to me!

**Pull request merged**
